# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nick Smith
email: nick6smith23@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Created this site for a class project. Using this to test everything out.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: @nicksmith623
github_username:  nsmith21

# Build settings
markdown: kramdown
